const hunterDB = {
  // 인물 데이터베이스
  characters: [
    // ==========================================
    // 🇰🇷 헌터 협회 (Association)
    // ==========================================
    {
      id: "kwon-jae-hyun",
      nameK: "권재현",
      nameE: "Kwon Jae-hyun",
      age: 67,
      rank: "S",
      group: "hunter_association",
      groupName: "헌터 협회",
      role: "협회장 / 전 S급",
      desc: "3세대 최강의 헌터였으나 현재는 지병으로 은퇴 후 행정에 전념. 협회의 기둥이자 정신적 지주.",
      image: "Kwon Jae-hyun.default.webp",
    },
    {
      id: "baek-hwi-sung",
      nameK: "백휘성",
      nameE: "Baek Hwi-Sung",
      age: 30,
      rank: "S",
      group: "hunter_association",
      groupName: "협회 (감찰국)",
      role: "국장 / 딜러",
      desc: "헌터를 사냥하는 헌터. 히든 클래스 '헬리오스의 전령'. 범죄 헌터와 PK범을 가차 없이 처단한다.",
      image: "Baek Hwi-Sung.default.webp",
    },
    {
      id: "choi-tae-hyun",
      nameK: "최태현",
      nameE: "Choi Tae-hyun",
      age: 36,
      rank: "B",
      group: "hunter_association",
      groupName: "협회 (감찰국)",
      role: "팀장 / 근접 딜러",
      desc: "감찰국 현장 팀장. 한쪽 눈을 잃은 베테랑으로, 능글맞은 태도 뒤에 날카로운 살기를 숨기고 있다.",
      image: "Choi Tae-hyun.default.webp",
    },
    {
      id: "yoo-jin-seong",
      nameK: "유진성",
      nameE: "Yoo Jin-seong",
      age: 27,
      rank: "D",
      group: "hunter_association",
      groupName: "협회 (기술지원팀)",
      role: "엔지니어 / 대장장이",
      desc: "협회 7층의 괴짜 엔지니어. '화력 만능주의'를 외치며 장비를 개조하는 것을 즐긴다.",
      image: "Yoo Jin-seong.default.webp",
    },
    {
      id: "choi-yoo-jin",
      nameK: "최유진",
      nameE: "Choi Yoo-jin",
      age: 24,
      rank: "N",
      group: "hunter_association",
      groupName: "협회 (등록팀)",
      role: "팀장 / 행정관",
      desc: "등록 및 측정팀 최연소 팀장. 비각성자지만 유단자이며, 철저한 원칙주의자로 업무를 처리한다.",
      image: "Choi Yoo-jin.default.webp",
    },
    {
      id: "go-eun-bi",
      nameK: "고은비",
      nameE: "Go Eun-bi",
      age: 22,
      rank: "N",
      group: "hunter_association",
      groupName: "협회 (등록팀)",
      role: "주임 / 행정직",
      desc: "최유진 팀장의 부사수. 헌터를 동경하여 입사했으며, 서툴지만 성실하게 업무를 수행한다.",
      image: "Go Eun-bi.default.webp",
    },
    {
      id: "park-hye-in",
      nameK: "박혜인",
      nameE: "Park Hye-in",
      age: 31,
      rank: "N",
      group: "hunter_association",
      groupName: "협회 (연구소)",
      role: "선임연구원",
      desc: "마나 병리학 박사. 포션 독성 검사의 최종 결재자. 깐깐하고 신경질적이지만 실력은 확실하다.",
      image: "Park Hye-in.default.webp",
    },
    {
      id: "lee-so-yoon",
      nameK: "이소윤",
      nameE: "Lee So-yoon",
      age: 28,
      rank: "N",
      group: "hunter_association",
      groupName: "협회 (정산팀)",
      role: "대리 / 행정직",
      desc: "정산 창구의 마스코트. 밝고 사교적인 성격으로 헌터들 사이에서 인기가 많다. 향기에 민감하다.",
      image: "Lee So-yoon.default.webp",
    },
    {
      id: "rivea",
      nameK: "리베아",
      nameE: "Rivea",
      age: 12, // 외관 나이
      rank: "D", // 추정
      group: "hunter_association",
      groupName: "협회 (보호대상)",
      role: "히든 클래스",
      desc: "협회 지하 시설에 격리된 수수께끼의 소녀. '잊혀진 신격' 클래스를 보유했으며 마나를 갈구한다.",
      image: "Rivea.default.webp",
    },

    // ==========================================
    // 🐺 은랑 길드 (Eunrang)
    // ==========================================
    {
      id: "im-jin-tae",
      nameK: "임진태",
      nameE: "Im Jin-tae",
      age: 41,
      rank: "S",
      group: "eunrang",
      groupName: "은랑 길드",
      role: "길드마스터 / 딜러",
      desc: "은랑의 마스터. '늑대 인간' 히든 클래스. 호탕한 성격이지만 적에게는 자비가 없다.",
      image: "Im Jin-tae.default.webp",
    },
    {
      id: "yoo-sun-hwa",
      nameK: "유선화",
      nameE: "Yoo Sun-hwa",
      age: 25,
      rank: "A",
      group: "eunrang",
      groupName: "은랑 길드",
      role: "딜러 / 관리자",
      desc: "길드 지하 투기장 '무쇠 천칭'의 관리자. 주먹으로 대화하는 것을 즐기는 전투광.",
      image: "Yoo Sun-hwa.default.webp",
    },
    {
      id: "park-so-won",
      nameK: "박소원",
      nameE: "Park So-won",
      age: 25,
      rank: "C",
      group: "eunrang",
      groupName: "은랑 길드",
      role: "서포터 / 연금술사",
      desc: "커다란 배낭을 메고 다니는 성실한 서포터. 코에 난 상처는 임진태를 동경해 그린 가짜다.",
      image: "Park So-won.default.webp",
    },

    // ==========================================
    // 🌸 백련 길드 (Baekryeon)
    // ==========================================
    {
      id: "yoon-mirae",
      nameK: "윤미래",
      nameE: "Yoon Mirae",
      age: 29,
      rank: "N",
      group: "baekryeon",
      groupName: "백련 길드",
      role: "길드마스터 / 전략가",
      desc: "비각성자임에도 예지 능력을 통해 길드를 이끄는 천재 전략가. 헌터 육성에 힘쓴다.",
      image: "Yoon Mirae.default.webp",
    },
    {
      id: "kang-woo-seok",
      nameK: "강우석",
      nameE: "Kang Woo-seok",
      age: 25,
      rank: "A",
      group: "baekryeon",
      groupName: "백련 길드",
      role: "탱커",
      desc: "과묵하고 듬직한 방패. 과거 동료를 잃은 트라우마로 인해 방어에 집착하는 경향이 있다.",
      image: "Kang Woo-seok.default.webp",
    },
    {
      id: "lim-seol-hee",
      nameK: "임설희",
      nameE: "Lim Seol-hee",
      age: 26,
      rank: "A",
      group: "baekryeon",
      groupName: "백련 길드",
      role: "마법사 (얼음)",
      desc: "'얼음 공주'라 불리는 유명 헌터. 대외적으로는 차갑지만 실제로는 평범한 삶을 동경한다.",
      image: "Lim Seol-hee.default.webp",
    },

    // ==========================================
    // 🐯 적호 길드 (Jeokho)
    // ==========================================
    {
      id: "choi-tae-joon",
      nameK: "최태준",
      nameE: "Choi Tae-joon",
      age: 40,
      rank: "A",
      group: "jeokho",
      groupName: "적호 길드",
      role: "길드마스터 / 사령관",
      desc: "최태현의 형. 흡연가이자 전략 덕후. S급 2명을 보유한 소수 정예 길드를 지휘한다.",
      image: "Choi Tae-joon.default.webp",
    },
    {
      id: "park-jun-ho",
      nameK: "박준호",
      nameE: "Park Jun-ho",
      age: 38,
      rank: "S",
      group: "jeokho",
      groupName: "적호 길드",
      role: "메인 탱커",
      desc: "유도 선수 출신의 S급 탱커. '벽운갑주' 클래스로 전방을 책임지는 든든한 가장.",
      image: "Park Jun-ho.default.webp",
    },
    {
      id: "han-ji-won",
      nameK: "한지원",
      nameE: "Han Ji-won",
      age: 26,
      rank: "S",
      group: "jeokho",
      groupName: "적호 길드",
      role: "서포터 (결계)",
      desc: "국내 유일의 S급 서포터. '진실의 시선'으로 정보를 꿰뚫어보며 인재 발굴을 즐긴다.",
      image: "Han Ji-won.default.webp",
    },

    // ==========================================
    // 🐍 흑사 길드 (Heuksa)
    // ==========================================
    {
      id: "joo-ah-ram",
      nameK: "주아람",
      nameE: "Joo Ah-ram",
      age: 29,
      rank: "B",
      group: "heuksa",
      groupName: "흑사 길드",
      role: "길드마스터",
      desc: "'검은 뱀들의 여왕'. 해외 파견 위주의 사업을 펼치며, 정보와 협상의 달인이다.",
      image: "Joo Ah-ram.default.webp",
    },
    {
      id: "jin-so-hee",
      nameK: "진소희",
      nameE: "Jin So-hee",
      age: 26,
      rank: "A",
      group: "heuksa",
      groupName: "흑사 길드",
      role: "부적술사 / 경호",
      desc: "주아람의 경호원이자 도박 중독자. 강력한 퇴마 부적을 사용한다.",
      image: "Jin So-hee.default.webp",
    },
    {
      id: "kang-min-hyuk",
      nameK: "강민혁",
      nameE: "Kang Min-hyuk",
      age: 24,
      rank: "A",
      group: "heuksa",
      groupName: "흑사 길드",
      role: "검사 (딜러)",
      desc: "실리주의자 검사. 불필요한 위험을 극도로 꺼리며, 깔끔한 일 처리를 선호한다.",
      image: "Kang Min-hyuk.default.webp",
    },

    // ==========================================
    // 🕊️ 프리랜서 / 기타 (Freelancer)
    // ==========================================
    {
      id: "jake-miller",
      nameK: "제이크 밀러",
      nameE: "Jake Miller",
      age: 32,
      rank: "S",
      group: "freelancer",
      groupName: "프리랜서",
      role: "무투가",
      desc: "한국계 미국인 S급 헌터. 맨손 격투의 달인이며 성격이 매우 거칠고 호전적이다.",
      image: "Jake Miller.default.webp",
    },
    {
      id: "ha-wol-young",
      nameK: "하월영",
      nameE: "Ha Wol-young",
      age: 28,
      rank: "S",
      group: "freelancer",
      groupName: "프리랜서",
      role: "검귀 (탱커?)",
      desc: "술을 사랑하는 S급 낭인. 세 자루의 유니크 카타나를 사용하며, 취했을 때 더 강하다.",
      image: "Ha Wol-young.default.webp",
    },
    {
      id: "alice-croft",
      nameK: "앨리스 크로프트",
      nameE: "Alice Croft",
      age: 22,
      rank: "A",
      group: "freelancer",
      groupName: "연구원",
      role: "서포터 (시간)",
      desc: "영국 출신의 천재. '크로노스의 후계자' 클래스 부작용으로 어린아이의 모습을 하고 있다.",
      image: "Alice Croft.default.webp",
    },
    {
      id: "lee-ji-hye",
      nameK: "이지혜",
      nameE: "Lee Ji-hye",
      age: 28,
      rank: "A",
      group: "freelancer",
      groupName: "프리랜서",
      role: "소환사 (Nyx)",
      desc: "만성 귀차니즘 헌터. 생활비만 벌면 활동을 중단한다. 그림자를 다루는 능력이 있다.",
      image: "Lee Ji-hye.default.webp",
    },
    {
      id: "sasaki-yua",
      nameK: "사사키 유아",
      nameE: "Sasaki Yua",
      age: 25,
      rank: "A",
      group: "freelancer",
      groupName: "프리랜서",
      role: "저승 무사",
      desc: "일본 몰락 무가 출신. 가문의 부흥을 위해 한국에서 활동 중인 성실한 검사.",
      image: "Sasaki Yua.default.webp",
    },
    {
      id: "min-chae-rin",
      nameK: "민채린",
      nameE: "Min Chae-rin",
      age: 24,
      rank: "B",
      group: "freelancer",
      groupName: "프리랜서",
      role: "암살자 (그림자)",
      desc: "고양이 귀와 꼬리를 가진 헌터. 과거의 상처로 인해 타인을 밀어내지만 속은 여리다.",
      image: "Min Chae-rin.default.webp",
    },
    {
      id: "han-seo-yeon",
      nameK: "한서연",
      nameE: "Han Seo-yeon",
      age: 23,
      rank: "B",
      group: "freelancer",
      groupName: "프리랜서",
      role: "화염 마법사",
      desc: "한지원의 여동생. 언니에 대한 열등감으로 위험한 힘에 손을 대며 폭주하려 한다.",
      image: "Han Seo-yeon.default.webp",
    },
    {
      id: "haru-ito",
      nameK: "하루 이토",
      nameE: "Haru Ito",
      age: 16,
      rank: "B",
      group: "freelancer",
      groupName: "프리랜서",
      role: "정령사",
      desc: "한일 혼혈의 소년 정령사. 식물과 바람 정령을 다루며, 자연 친화적인 성격이다.",
      image: "Haru Ito.default.webp",
    },
    {
      id: "choi-min-jun",
      nameK: "최민준",
      nameE: "Choi Min-jun",
      age: 35,
      rank: "C",
      group: "freelancer",
      groupName: "스톤 스퀘어",
      role: "탱커 / 멘토",
      desc: "신입 헌터들의 안전을 책임지는 멘토. '스톤 스퀘어' 사무소를 운영한다.",
      image: "Choi Min-jun.default.webp",
    },
    {
      id: "seo-ji-han",
      nameK: "서지한",
      nameE: "Seo Ji-han",
      age: 26,
      rank: "C",
      group: "freelancer",
      groupName: "프리랜서",
      role: "서포터 (저주)",
      desc: "레드 게이트 생존자. 흡혈귀의 저주를 받아 피를 갈구하지만 이성을 유지하려 애쓴다.",
      image: "Seo Ji-han.default.webp",
    },
    {
      id: "kang-yoo-ra",
      nameK: "강유라",
      nameE: "Kang Yoo-ra",
      age: 27,
      rank: "C",
      group: "freelancer",
      groupName: "직장인",
      role: "스트라이커",
      desc: "본업은 콜센터 대리, 부업이 헌터. 퇴근 후 스트레스 해소용으로 몬스터를 때려잡는다.",
      image: "Kang Yoo-ra.default.webp",
    },
    {
      id: "lee-ha-eun",
      nameK: "이하은",
      nameE: "Lee Ha-eun",
      age: 21,
      rank: "D",
      group: "freelancer",
      groupName: "프리랜서",
      role: "힐러 (클레릭)",
      desc: "겁이 많고 소심하지만, 위급한 순간에는 동료를 위해 용기를 내는 성직자.",
      image: "Lee Ha-eun.default.webp",
    },
    {
      id: "isabelle-hayes",
      nameK: "이사벨 헤이즈",
      nameE: "Isabelle Hayes",
      age: 20,
      rank: "D",
      group: "freelancer",
      groupName: "프리랜서",
      role: "성기사",
      desc: "영국 출신의 독실한 신자. 게이트를 악으로 규정하고 정화하기 위해 싸운다.",
      image: "Isabelle Hayes.default.webp",
    },
    {
      id: "kim-min-soo",
      nameK: "김민수",
      nameE: "Kim Min-soo",
      age: 20,
      rank: "E",
      group: "freelancer",
      groupName: "프리랜서",
      role: "탱커 (어그로)",
      desc: "관종끼가 다분한 E급 탱커. '이목 집중' 스킬 하나만 믿고 나대지만 미워할 수 없다.",
      image: "Kim Min-soo.default.webp",
    },
    {
      id: "song-ha-neul",
      nameK: "송하늘",
      nameE: "Song Ha-neul",
      age: 20,
      rank: "E",
      group: "freelancer",
      groupName: "프리랜서",
      role: "궁수",
      desc: "가장의 무게를 짊어진 소녀 가장. 징그러운 것을 싫어하지만 가족을 위해 활을 든다.",
      image: "Song Ha-neul.default.webp",
    },
    {
      id: "ahn-do-hyun",
      nameK: "안도현",
      nameE: "Ahn Do-hyun",
      age: 25,
      rank: "E",
      group: "freelancer",
      groupName: "프리랜서",
      role: "수리공",
      desc: "전투 능력은 없지만 탁월한 손재주로 장비를 수리하는 맥가이버.",
      image: "Ahn Do-hyun.default.webp",
    },
    {
      id: "oh-ha-na",
      nameK: "오하나",
      nameE: "Oh Ha-na",
      age: 20,
      rank: "E",
      group: "freelancer",
      groupName: "프리랜서",
      role: "투척가",
      desc: "헌터물을 덕질하다가 진짜 헌터가 된 '성덕'. 만화 속 기술 이름을 외치며 싸운다.",
      image: "Oh Ha-na.default.webp",
    },
    {
      id: "choi-yu-na",
      nameK: "최유나",
      nameE: "Choi Yu-na",
      age: 17,
      rank: "E",
      group: "freelancer",
      groupName: "학생",
      role: "탱커",
      desc: "최유진의 사촌 동생. 방어력 패시브를 가진 학생 헌터. 틱틱대지만 속은 깊다.",
      image: "Choi Yu-na.default.webp",
    },
    {
      id: "yoon-ji-ho",
      nameK: "윤지호",
      nameE: "Yoon Ji-ho",
      age: 14,
      rank: "N",
      group: "freelancer",
      groupName: "블랙마켓",
      role: "정보상 / 감정사",
      desc: "암시장의 꼬마 정보상. 아이템의 가치를 본능적으로 꿰뚫어 보는 능력이 있다.",
      image: "Yoon Ji-ho.default.webp",
    },
    {
      id: "baek-eun-ha",
      nameK: "백은하",
      nameE: "Baek Eun-ha",
      age: 24,
      rank: "N",
      group: "freelancer",
      groupName: "민간인",
      role: "백휘성의 여동생",
      desc: "오랜 코마 상태에서 깨어나 재활 중인 백휘성의 여동생. 꽃을 좋아한다.",
      image: "Baek Eun-ha.default.webp",
    },

    // ==========================================
    // 😈 적대 세력 / 빌런 (Villain)
    // ==========================================
    {
      id: "kwon-do-yoon",
      nameK: "권도윤",
      nameE: "Kwon Do-yoon",
      age: 27,
      rank: "B",
      group: "villain",
      groupName: "블랙마켓 간부",
      role: "지략가",
      desc: "협회에 대한 복수심으로 암시장을 장악한 지략가. '암시' 스킬로 사람을 조종한다.",
      image: "Kwon Do-yoon.default.webp",
    },
    {
      id: "kang-tae-shik",
      nameK: "강태식",
      nameE: "Kang Tae-shik",
      age: 29,
      rank: "C", // 실제 전투력은 더 높음
      group: "villain",
      groupName: "PK 수배범",
      role: "살인마",
      desc: "초보 헌터 파티에 잠입해 살육을 즐기는 연쇄 살인마. 뱀 같은 눈을 가졌다.",
      image: "Kang Tae-shik.default.webp",
    },
    {
      id: "yoo-jin-hyuk",
      nameK: "유진혁",
      nameE: "Yoo Jin-hyuk",
      age: 31,
      rank: "A", // 전 A급
      group: "villain",
      groupName: "도망자",
      role: "PK / 어둠",
      desc: "백휘성에게 눈을 잃고 복수를 꿈꾸는 타락한 헌터. 어둠을 다루는 능력이 있다.",
      image: "Yoo Jin-hyuk.default.webp",
    },
    {
      id: "jang-eun-seo",
      nameK: "장은서",
      nameE: "Jang Eun-seo",
      age: 27,
      rank: "N", // 측정 불가
      group: "villain",
      groupName: "불신론자 리더",
      role: "테러리스트",
      desc: "상태창 불신론자의 리더. 저주 아이템의 페널티를 무시하는 특이 체질 보유자.",
      image: "Jang Eun-seo.default.webp",
    },
    {
      id: "chae-ha-yoon",
      nameK: "채하윤",
      nameE: "Chae Ha-yoon",
      age: 26,
      rank: "E", // 전 E급
      group: "villain",
      groupName: "불신론자 부관",
      role: "마탄 사수",
      desc: "장은서의 오른팔. 쌍권총과 마력 탄환을 사용하는 쾌락주의자 테러리스트.",
      image: "Chae Ha-yoon.default.webp",
    },
    {
      id: "shin-woo-hyun",
      nameK: "신우현",
      nameE: "Shin Woo-hyun",
      age: 27,
      rank: "N",
      group: "villain",
      groupName: "이계 숭배단",
      role: "등불 (간부)",
      desc: "광신도 집단의 간부. 오염된 마석을 사용하여 기괴한 힘을 휘두른다.",
      image: "Shin Woo-hyun.default.webp",
    },
    {
      id: "na-sun-young",
      nameK: "나선영",
      nameE: "Na Sun-young",
      age: 28,
      rank: "A", // 추정
      group: "villain",
      groupName: "이계 숭배단",
      role: "등불 (저주)",
      desc: "레드 게이트 생존자이자 광신도. 마나를 시각적으로 보는 능력이 있다.",
      image: "Na Sun-young.default.webp",
    },
  ],
};
